version: "3.8"

services:
  account:
    build: "src/account/"
    command: "npm run account"
    ports: 
      - "5000:5000" 
    env_file: "src/account/.env"
    dns:
      - "8.8.8.8"
  routes:
    build: "src/routes/"
    command: "npx ts-node github.ts"
    ports:
      - "4000:4000"
      - "8080:8080"
    env_file: "src/routes/.env"
#   client:
#     build: "client/"
#     command: "npm start"
#     ports:
#       - "3000:3000"
#     env_file: ".env"
# # Requires server services to run before running client servers
#     depends_on:
#       - "server"
