version: '2.21'

services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.10.2"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node1:/usr/share/elasticsearch/data