version: "3.8"

services:
  account:
    build: "src/account/"
    command: "npm run account"
    ports: 
      - "5000:5000" 
    env_file: "src/account/.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - "8.8.8.8"
    network_mode: "host"
#   client:
#     build: "client/"
#     command: "npm start"
#     ports:
#       - "3000:3000"
#     env_file: ".env"
# # Requires server services to run before running client servers
#     depends_on:
#       - "server"
