# Use the official ActiveMQ image as the base image
FROM webcenter/activemq:latest

# Specifies /app as working directory in docker image
WORKDIR /app

# Copy only package.json to leverage Docker caching
COPY package.json /app/package.json
COPY .env /app/.env

# Install any necessary dependencies
RUN npm install

# Copy the rest of the files to the working directory
COPY config.ts /app/config.ts
COPY NotiInterfaceinterface.ts /app/NotiInterface.ts
COPY docker-compose.yaml /app/docker-compose.yaml

COPY MessageConsumer.js /app/MessageConsumer.js
COPY MessageDeleter.js /app/MessageDeleter.js
COPY MessageProducer.js /app/MessageProducer.js
COPY MessageScheduler.js /app/MessageScheduler.js

# Expose ActiveMQ ports (61613 for STOMP, 8161 for the management web UI)
EXPOSE 61613 8161

# Start your ActiveMQ service when the container starts
CMD ["npm", "start"]