version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    restart: always
    env_file: ".env"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq_go_net
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

networks:
  rabbitmq_go_net:
    driver: bridge