version: '3'
services:
  activemq:
    image: webcenter/activemq:latest
    container_name: my-activemq-container
    ports:
      - "61613:61613"
      - "8161:8161"
    env_file:
      - .env