# Workflow to codecov

name: Run codecov
# Runs on push to any branch
on:
  push:
  pull_request:
    branches:
    - master
  # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  # Run tests
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 
      - uses: actions/setup-python@v4
        name: Set up Python 3.10
        with:
          python-version: '3.10'
      - name: Install python dependencies
        run: pip install -r controller/requirements.txt
      - name: Run unit tests with code coverage
        run: coverage run -m pytest 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        timeout-minutes: 1
