# Workflow to codecov

name: Run codecov
# Runs on push to any branch
on:
  push:
  pull_request:
    branches:
    - master
  # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  # Run tests
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        timeout-minutes: 1
