# This is a basic workflow to help you get started with Actions

name: luminosityled.com update

# Controls when the workflow will run
on:
  # Triggers the workflow on push events only to the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under ${{ github.workspace }}, so your job can access it.  Fetches most recent commit for all branches and tags
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      # Setup nodejs on runner
      - uses: actions/setup-node@v3
        with: 
          node-version: 16

      # Install the npm dependencies & build the react website
      - name: Build react website 
        run: |
          cd client
          npm install && npm run build
      
      # Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/build
          force_orphan: true
          cname: luminosityleds.com

      
