name: Lint Python Code with Pylint

# Runs on push and pull requests to the master branch only
on:
  push:
   branches: "master"
  pull_request:
   branches: "master"
 # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # Install package manager and pylint
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    # Default score to pass is 10, 0 on fatal error
    - name: Run Pylint
      run: |
       pylint $(git ls-files '*.py')
