# Workflow to run backend tests 

name: Run backend tests

# Runs on push to any branch
on:
  push:
  pull_request:
    branches:
    - master
  # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  # Run tests
  test_login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Run backend checks
        run: |
          npm install
          npm run test -- src/tests/
        timeout-minutes: 1