# https://github.com/marketplace/actions/jest-coverage-report
# By default, uses npm for package manager
name: Typescript Coverage

# Runs on push to any branch
on:
  push:
    # ** means all branches and tags
    branches: ["**"]
  # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:
  
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
